version: '2'
services:
  nginx:
    image: nginx:1.9.6
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "8080:8080"
    volumes_from:
      - frontend

  mongo:
    image: mongo:3.0
    command: mongod --smallfiles
    volumes:
      - mongoDbdata:/data/db

  api_server:
    build: ./pythonDocker
    volumes:
      - ./api:/usr/src/app
    environment:
      MONGOLAB_URI: "mongodb://mongo:27017/development"
      DEVELOPMENT: "true"

  frontend:
  #  build: ./frontendDocker
    image: library/node
    command: /usr/local/bin/npm start --cache=/data/.npm
    working_dir: /data
    volumes:
      - ./:/data
volumes:
  mongoDbdata: {}